Mons level 100 gain EVs from battle
BuffelSaft/pokeemerald pull request #295
Opened 2021-11-10 13:06 UTC by kleeenexfeu

2021-11-10 13:38 UTC, kleeenexfeu commented
Noticed a bug in the original function.
Griffin put it in better words than I ever could there : https://github.com/pret/pokeemerald/blob/master/src/pokemon.c#L5780-L5785

2021-11-11 02:44 UTC, BuffelSaft requested changes

2021-11-11 02:44 UTC, BuffelSaft commented on src/battle_ai_util.c
> +    // Do not calculate effectiveness for status moves. However if the move is thunderwave and is used against an immunity, go to the switch idiom
Electric's immunity to paralysis is already handled in `AI_CanBeParalyzed`. As of gen 6 all moves that paralyze won't paralyze an electric type, so a check for Thunder Wave isn't needed here.

2021-11-11 10:54 UTC, kleeenexfeu commented on src/battle_ai_util.c
> +    // Do not calculate effectiveness for status moves. However if the move is thunderwave and is used against an immunity, go to the switch idiom
What about ground types ? Did you fix the AI using twave on ground types?

2021-11-11 13:19 UTC, closed without merging